name: E2E Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_DEPLOY_KEY: ${{ secrets.GH_DEPLOY_KEY }}
    steps:
      - run: echo "CI=true" >> $GITHUB_ENV
      - name: Checkout 🛎️
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: yarn
      - run: yarn playwright install-deps
      - run: yarn playwright install
      - run: yarn test
