name: Lint

on: pull_request

jobs:
  eslint:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v1
      - uses: hallee/eslint-action@master
