name: Android Publish

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@master
        with:
          node-version: '16'

      - name: Use specific Java version for the builds
        uses: joschi/setup-jdk@v2
        with:
          java-version: '11'
          architecture: 'x64'

      - name: Install node modules
        run: |
          npm ci
      - name: Make Gradlew Executable
        run: cd apps/mobile/native/android && chmod +x ./gradlew

      - name: Build Android App Bundle
        run: |
          cd apps/mobile/native/android && ./gradlew bundleRelease --no-daemon

      - name: Build Android App APKS
        run: |
          cd apps/mobile/native/android && GITHUB_RELEASE=true ENVFILE=.env.public ./gradlew assembleRelease --no-daemon